module.exports = {
	MAUS: 			{ name: "Maus",			filename: "Maus",           timeOfDay: ["Night"],       season: ["Winter"]},
	FROSCH: 		{ name: "Frosch",		filename: "Frosch",         timeOfDay: ["Day"],         season: ["Summer"]},
	BAER: 			{ name: "Bär",			filename: "Bär",            timeOfDay: ["Day", "Night"],season: ["Winter", "Autumn"]},
	BIENE: 			{ name: "Biene",		filename: "Biene",          timeOfDay: ["Day"] ,        season: ["Spring", "Summer"]},
	DACHS: 			{ name: "Dachs",		filename: "Dachs",          timeOfDay: ["Night"],       season: ["Autumn", "Winter"]},
	ENTE: 			{ name: "Ente",			filename: "Ente",           timeOfDay: ["Day"],         season: ["Spring", "Summer", "Autumn"]},
	FUCHS:          { name: "Fuchs",        filename: "Fuchs",          timeOfDay: ["Day", "Night"],season: ["Winter", "Autumn"] },
    HASE:           { name: "Hase",         filename: "Hase",           timeOfDay: ["Day"],         season: ["Spring", "Autumn"] },
    MARIENKAEFER:   { name: "Marienkäfer",  filename: "Marienkäfer",    timeOfDay: ["Day"],         season: ["Spring", "Summer"] },
    REH:            { name: "Reh",          filename: "Reh",            timeOfDay: ["Day"],         season: ["Spring", "Summer", "Autumn"] },
    SPECHT:         { name: "Specht",       filename: "Specht",         timeOfDay: ["Day"],         season: ["Spring", "Summer", "Autumn"] },
    WOLF:           { name: "Wolf",         filename: "Wolf",           timeOfDay: ["Day", "Night"],season: ["Winter", "Autumn"] },
    WASCHBAER:      { name: "Waschbär",     filename: "Waschbaer",      timeOfDay: ["Night"],       season: ["Summer", "Autumn"] },
    EICHHOERNCHEN:  { name: "Eichhörnchen", filename: "Eichhoernchen",  timeOfDay: ["Day"],         season: ["Spring", "Summer", "Autumn"] },
    SCHILDKROETE:   { name: "Schildkröte",  filename: "Schildkroete",   timeOfDay: ["Day"],         season: ["Summer"] },

    AFFE:           { name: "Affe",         filename: "Affe",           timeOfDay: ["Day"],         season: ["Summer"] },
    ELEFANT:        { name: "Elefant",      filename: "Elefant",        timeOfDay: ["Day"],         season: ["Summer"] },
    EULE:           { name: "Eule",         filename: "Eule",           timeOfDay: ["Night"],       season: ["Autumn", "Winter"] },
    FLEDERMAUS:     { name: "Fledermaus",   filename: "Fledermaus",     timeOfDay: ["Night"],       season: ["Spring", "Summer", "Autumn"] },
    HAMSTER:        { name: "Hamster",      filename: "Hamster",        timeOfDay: ["Night"],       season: ["Spring", "Summer", "Autumn"] },
    HUND:           { name: "Hund",         filename: "Hund",           timeOfDay: ["Day", "Night"],season: ["Spring", "Autumn", "Winter"] },
    IGEL:           { name: "Igel",         filename: "Igel",           timeOfDay: ["Night"],       season: ["Spring", "Summer", "Autumn"] },
    KATZE:          { name: "Katze",        filename: "Katze",          timeOfDay: ["Night"],       season: ["Spring", "Summer", "Autumn"] },
    LOEWE:          { name: "Löwe",         filename: "Löwe",           timeOfDay: ["Day"],         season: ["Summer"] },
    PANDA:          { name: "Panda",        filename: "Panda",          timeOfDay: ["Day"],         season: ["Spring", "Summer", "Autumn"] },
    PAPAGEI:        { name: "Papagei",      filename: "Papagei",        timeOfDay: ["Day"],         season: ["Summer"] },
    REDPANDA:       { name: "Red Panda",    filename: "Redpanda",       timeOfDay: ["Day"],         season: ["Spring", "Autumn"] },
    TIGER:          { name: "Tiger",        filename: "Tiger",          timeOfDay: ["Night"],       season: ["Summer"] },
    WILDSCHWEIN:    { name: "Wildschwein",  filename: "Wildschwein",    timeOfDay: ["Day", "Night"],season: ["Winter", "Autumn"] },
    ZEBRA:          { name: "Zebra",        filename: "Zebra",          timeOfDay: ["Day"],         season: ["Summer"] },
}
